### ISSUE TITLE
mocha test issue

### ISSUE THREAD

**Issue by yrq110** [unix/koa-ts#15]
Type:
- [x] Bug
- [ ] Feature
- [ ] Help   

Description:

Follow these steps:
1. git clone git@github.com:unix/koa-ts.git
2. yarn install
3. yarn test

Output error message:

```
yarn test
$ mocha
Error: Cannot find module 'configs/utils'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/foo/Desktop/source/koa-ts/app.ts:2:1)
    at Module._compile (module.js:652:30)
    at Module.m._compile (/Users/foo/Desktop/source/koa-ts/node_modules/ts-node/src/index.ts:439:23)
    at Module._extensions..js (module.js:663:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/Users/foo/Desktop/source/koa-ts/node_modules/ts-node/src/index.ts:442:12)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/foo/Desktop/source/koa-ts/test/utils.nyc.ts:4:1)
    at Module._compile (module.js:652:30)
    at Module.m._compile (/Users/foo/Desktop/source/koa-ts/node_modules/ts-node/src/index.ts:439:23)
    at Module._extensions..js (module.js:663:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/Users/foo/Desktop/source/koa-ts/node_modules/ts-node/src/index.ts:442:12)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/foo/Desktop/source/koa-ts/test/apis/session.ts:1:1)
    at Module._compile (module.js:652:30)
    at Module.m._compile (/Users/foo/Desktop/source/koa-ts/node_modules/ts-node/src/index.ts:439:23)
    at Module._extensions..js (module.js:663:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/Users/foo/Desktop/source/koa-ts/node_modules/ts-node/src/index.ts:442:12)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at /Users/foo/Desktop/source/koa-ts/node_modules/mocha/lib/mocha.js:250:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/Users/foo/Desktop/source/koa-ts/node_modules/mocha/lib/mocha.js:247:14)
    at Mocha.run (/Users/foo/Desktop/source/koa-ts/node_modules/mocha/lib/mocha.js:576:10)
    at Object.<anonymous> (/Users/foo/Desktop/source/koa-ts/node_modules/mocha/bin/_mocha:637:18)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
error Command failed with exit code 1.
```

**Comment by unix** [comment]
Hi, sorry for the late reply, and your issue has been fixed here: #17 .
